import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding.x = 10
padding.y = 10

# opacity = 0.8

[font]
normal = { family = "JetBrains Mono Nerd Font"}

[env]
TERM = "xterm-256color"
